app.controller("infocontroller", function($scope){
    $scope.info =[{
            "firstName":"Mohamed",
            "lastName":"Badr",
            "age":20,
            "dept":"SD"
        },
        {
            "firstName":"Amr",
            "lastName":"Ali",
            "age":40,
            "dept":"QA"
        },
        {
            "firstName":"Sara",
            "lastName":"Hassan",
            "age":25,
            "dept":"SD"
        },
        {
            "firstName":"Yara",
            "lastName":"Adel",
            "age":33,
            "dept":"MM"
        },
        {
            "firstName":"Hany",
            "lastName":"Mostafa",
            "age":42,
            "dept":"OS"
        },
        {
            "firstName":"Sayed",
            "lastName":"Kamal",
            "age":37,
            "dept":"EL"
        }];
})